apiVersion: v1
kind: ConfigMap
metadata:
  name: citizens-transfer-api
  namespace: citizens-folder
data:
  CORS_ORIGINS: localhost,*
  AMQP_HOST: production-rabbitmqcluster.rabbitmq-system.svc.cluster.local
  PORT: "8450"
  #FILES_URL: http://files-api
  #GOVCARPETA_URL: https://govcarpeta-apis-83e1c996379d.herokuapp.com
  #AMQP_QUEUE: document_to_certificate
  #AMQP_EXCHANGE: document_to_certificate
  #AMQP_ROUTING_KEY: document_to_certificate
  #AMQP_PORT: "5672"

