apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: citizens-transfer-api
  namespace: citizens-folder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: citizens-transfer-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
