apiVersion: v1
kind: Service
metadata:
  labels:
    app: citizens-transfer-api
  name: citizens-transfer-api
  namespace: citizens-folder
spec:
  selector:
    app: citizens-transfer-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8450
