apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-server-mailhog
  name: email-server-mailhog
  namespace: citizens-folder
spec:
  type: ClusterIP
  selector:
    app: email-server-mailhog
  ports:
  - name: smtp
    port: 1025
    protocol: TCP
    targetPort: 1025
  - name: http
    port: 8025
    protocol: TCP
    targetPort: 8025