apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: citizens-folder
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
