apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: citizens-folder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: spbpatino/citizens-folder-web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
