apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: citizens-folder
spec:
  selector:
    app: web-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
