apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: web-app
  namespace: citizens-folder
spec:
  virtualhost:
    fqdn: fastidentify.com 
    #tls:
    #  secretName: ambassador-tls
  routes:
    - conditions:
      - prefix: /
      