apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: web-app
  namespace: citizens-folder
spec:
  virtualhost:
    fqdn: fastidentify.com
    tls:
      secretName: citizens-folder-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: web-app  # Asegúrate de que este servicio exista y esté correctamente configurado
          port: 80
      