apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: web-app-www
  namespace: citizens-folder
spec:
  virtualhost:
    fqdn: www.fastidentify.com
    #tls:
    #  secretName: www-ambassador-tls
  routes:
    - conditions:
      - prefix: /
      requestRedirectPolicy:
        hostname: fastidentify.com