---
version: "3.8"
services:
  angular:
    build:
      context: ../../services/citizen_folder
      dockerfile: Dockerfile.development
    command: sh -c 'npm install && npm run ng serve --host 0.0.0.0 --port 4200 --disableHostCheck true'
    ports:
      - 4200:4200
    volumes:
      - ../../services/citizen_folder:/app
    networks:
      - app-network

networks:
  app-network:
