---
version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    expose:
      - 5672
    ports:
      - 15672:15672
    volumes:
      - ../rabbitmq/config/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app-network

networks:
  app-network:
