---
version: "3.8"
services:
  documents:
    build:
      context: ../../services/documents
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
    volumes:
      - ../../services/documents:/app
    command: ["python3", "src/main/documents.py"]
    networks:
      - app-network

  email_documents:
    build:
      context: ../../services/documents
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
    volumes:
      - ../../services/documents:/app
    command: ["python3", "src/main/email_documents.py"]
    networks:
      - app-network

  update_citizen_to_documents_worker:
    build:
      context: ../../services/documents
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
    volumes:
      - ../../services/documents:/app
    command: ["python3", "src/main/update_citizen_to_documents_worker.py"]
    networks:
      - app-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    expose:
      - 5672
    ports:
      - 15672:15672
    volumes:
      - ../rabbitmq/config/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - app-network

networks:
  app-network:
