apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-citizens-client-myphpadmin
  name: db-citizens-client-myphpadmin
  namespace: citizens-folder
spec:
  type: ClusterIP
  selector:
    app: db-citizens-client-myphpadmin
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80