apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-mongodb
  namespace: citizens-folder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documents-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: documents-mongodb
    spec:
      containers:
      - name: documents-mongodb
        image: mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"