apiVersion: v1
kind: Service
metadata:
  name: documents-mongodb
  namespace: citizens-folder
spec:
  selector:
    app: documents-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
