apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-ambassador-tls
spec:
  commonName: admin.ambassadors.ink
  dnsNames:
  - admin.ambassadors.ink
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: admin-ambassador-tls