apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ambassador-tls
spec:
  commonName: ambassadors.ink
  dnsNames:
  - ambassadors.ink
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: ambassador-tls