apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-fastidentify-tls
  namespace: citizens-folder
spec:
  commonName: api.fastidentify.com
  dnsNames:
  - api.fastidentify.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: api-fastidentify-tls