apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: citizens-folder-tls
spec:
  commonName: fastidentify.com
  dnsNames:
  - fastidentify.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: citizens-folder-tls