apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: email-ambassador-tls
spec:
  commonName: email.ambassadors.ink
  dnsNames:
  - email.ambassadors.ink
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: email-ambassador-tls