apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mailhog-ambassador-tls
spec:
  commonName: mailhog.ambassadors.ink
  dnsNames:
  - mailhog.ambassadors.ink
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: mailhog-ambassador-tls