apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-ambassador-tls
spec:
  commonName: redis.ambassadors.ink
  dnsNames:
  - redis.ambassadors.ink
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: redis-ambassador-tls