apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: usersdb-ambassador-tls
spec:
  commonName: usersdb.ambassadors.ink
  dnsNames:
  - usersdb.ambassadors.ink
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: usersdb-ambassador-tls