apiVersion: v1
kind: Service
metadata:
  name: docdb-core-redis
  namespace: ambassador-test
spec:
  type: ClusterIP
  selector:
    app: docdb-core-redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8001

