apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: docdb-core-redis
  name: docdb-core-redis
  namespace: ambassador-test
spec:
  virtualhost:
    fqdn: redis.ambassadors.ink
    tls:
      secretName: redis-ambassador-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: docdb-core-redis
          port: 80