apiVersion: apps/v1
kind: Deployment
metadata:
  name: docdb-core-redis
  namespace: ambassador-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docdb-core-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docdb-core-redis
    spec:
      containers:
      - name: docdb-core-redis
        image: redis/redis-stack
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        - containerPort: 8001
