apiVersion: v1
kind: Service
metadata:
  name: docdb-operators-redis
  namespace: citizens-folder
spec:
  type: ClusterIP
  selector:
    app: docdb-operators-redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8001

