apiVersion: apps/v1
kind: Deployment
metadata:
  name: docdb-operators-redis
  namespace: citizens-folder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docdb-operators-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docdb-operators-redis
    spec:
      containers:
      - name: docdb-operators-redis
        image: redis/redis-stack
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        - containerPort: 8001

