apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-ambassador-client-myphpadmin
  name: db-ambassador-client-myphpadmin
  namespace: ambassador-test
spec:
  type: ClusterIP
  selector:
    app: db-ambassador-client-myphpadmin
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80