apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: db-ambassador-client-myphpadmin
  name: db-ambassador-client-myphpadmin-coredb
  namespace: ambassador-test
spec:
  virtualhost:
    fqdn: coredb.ambassadors.ink
    tls:
      secretName: coredb-ambassador-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: db-ambassador-client-myphpadmin
          port: 80