apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 30007
    name: amqp
  - port: 15672
    targetPort: 15672
    nodePort: 30008
    name: management
  selector:
    app: rabbitmq