apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: rabbitmq-service
  name: rabbitmq-service
  namespace: rabbitmq
spec:
  virtualhost:
    fqdn: broker.fastidentify.com
    #tls:
    #  secretName: citizensdb-ambassador-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: rabbitmq-service
          port: 80