apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-citizens-mysql
  namespace: citizens-folder
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: db-citizens-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-citizens-mysql
    spec:
      containers:
      - name: db-citizens-mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: citizens
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
